/**
 * @author Dwight Van der Velpen
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelResultTeller = new javax.swing.JLabel();
        jLabelResultNoemer = new javax.swing.JLabel();
        jLabelResultTeller1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldTeller2 = new javax.swing.JTextField();
        jTextFieldNoemer2 = new javax.swing.JTextField();
        jLabelResultTeller2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldTeller1 = new javax.swing.JTextField();
        jLabelResultTeller3 = new javax.swing.JLabel();
        jTextFieldNoemer1 = new javax.swing.JTextField();
        jButtonPlus = new javax.swing.JButton();
        jButtonMin = new javax.swing.JButton();
        jButtonMaal = new javax.swing.JButton();
        jButtonDeel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("=");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelResultTeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultTeller.setText("1");

        jLabelResultNoemer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultNoemer.setText("1");

        jLabelResultTeller1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultTeller1.setText("-------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResultTeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelResultNoemer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelResultTeller1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelResultTeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultTeller1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultNoemer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldTeller2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTeller2.setText("1");

        jTextFieldNoemer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNoemer2.setText("1");

        jLabelResultTeller2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultTeller2.setText("-------------");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTeller2)
                    .addComponent(jLabelResultTeller2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jTextFieldNoemer2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTeller2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResultTeller2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNoemer2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldTeller1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTeller1.setText("1");

        jLabelResultTeller3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultTeller3.setText("-------------");

        jTextFieldNoemer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNoemer1.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTeller1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jTextFieldNoemer1))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelResultTeller3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldTeller1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNoemer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabelResultTeller3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonMin.setText("-");
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });

        jButtonMaal.setText("x");
        jButtonMaal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaalActionPerformed(evt);
            }
        });

        jButtonDeel.setText("/");
        jButtonDeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDeel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonMaal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMin)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonMaal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        Breuk b1 = new Breuk(Integer.parseInt(jTextFieldTeller1.getText()), Integer.parseInt(jTextFieldNoemer1.getText()));
        Breuk b2 = new Breuk(Integer.parseInt(jTextFieldTeller2.getText()), Integer.parseInt(jTextFieldNoemer2.getText()));
        Breuk b3 = b1.plus(b2);
        jLabelResultTeller.setText("" + b3.getTeller());
        jLabelResultNoemer.setText("" + b3.getNoemer());
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        Breuk b1 = new Breuk(Integer.parseInt(jTextFieldTeller1.getText()), Integer.parseInt(jTextFieldNoemer1.getText()));
        Breuk b2 = new Breuk(Integer.parseInt(jTextFieldTeller2.getText()), Integer.parseInt(jTextFieldNoemer2.getText()));
        Breuk b3 = b1.min(b2);
        jLabelResultTeller.setText("" + b3.getTeller());
        jLabelResultNoemer.setText("" + b3.getNoemer());
    }//GEN-LAST:event_jButtonMinActionPerformed

    private void jButtonMaalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaalActionPerformed
        Breuk b1 = new Breuk(Integer.parseInt(jTextFieldTeller1.getText()), Integer.parseInt(jTextFieldNoemer1.getText()));
        Breuk b2 = new Breuk(Integer.parseInt(jTextFieldTeller2.getText()), Integer.parseInt(jTextFieldNoemer2.getText()));
        Breuk b3 = b1.maal(b2);
        jLabelResultTeller.setText("" + b3.getTeller());
        jLabelResultNoemer.setText("" + b3.getNoemer());
    }//GEN-LAST:event_jButtonMaalActionPerformed

    private void jButtonDeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeelActionPerformed
        Breuk b1 = new Breuk(Integer.parseInt(jTextFieldTeller1.getText()), Integer.parseInt(jTextFieldNoemer1.getText()));
        Breuk b2 = new Breuk(Integer.parseInt(jTextFieldTeller2.getText()), Integer.parseInt(jTextFieldNoemer2.getText()));
        Breuk b3 = b1.deel(b2);
        jLabelResultTeller.setText("" + b3.getTeller());
        jLabelResultNoemer.setText("" + b3.getNoemer());
    }//GEN-LAST:event_jButtonDeelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeel;
    private javax.swing.JButton jButtonMaal;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelResultNoemer;
    private javax.swing.JLabel jLabelResultTeller;
    private javax.swing.JLabel jLabelResultTeller1;
    private javax.swing.JLabel jLabelResultTeller2;
    private javax.swing.JLabel jLabelResultTeller3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldNoemer1;
    private javax.swing.JTextField jTextFieldNoemer2;
    private javax.swing.JTextField jTextFieldTeller1;
    private javax.swing.JTextField jTextFieldTeller2;
    // End of variables declaration//GEN-END:variables
}
