
import java.awt.Color;
import java.awt.Graphics;

/**
 * @author DVDV
 */
public class Spelbord extends javax.swing.JPanel {
    public static final int RIJEN = 6;
    private static final int KOLOMMEN = 7;
    /**
     * Creates new form Spelbord
     */
    public Spelbord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        tekenBord(g);
    }
    
    private void tekenBord(Graphics g){
        int xFactor = getWidth() / KOLOMMEN;
        int yFactor = getHeight() / RIJEN;
        
        g.setColor(Color.BLACK);
        
        // HORZ
        g.drawLine(0, 0, getWidth(), 0);
        for (int i = 0; i < RIJEN; i++) {
            g.drawLine(0, i * yFactor, getWidth(), i * yFactor);
        }
        
        // VERT
        g.drawLine(0, 0, 0, getHeight());
        for (int i = 0; i < KOLOMMEN; i++) {
            g.drawLine(i * xFactor, 0, i * xFactor, getHeight());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
