/*
 * The MIT License
 *
 * Copyright 2018 dwigh.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 * @author Dwight Van der Velpen
 */
public class HogerLager extends javax.swing.JFrame {
    Spel spel;

    /**
     * Creates new form HogerLager
     */
    public HogerLager() {
        initComponents();
        
        // Maak een Spel object aan
        spel = new Spel();
        jButtonCorrect.setEnabled(false);
        jButtonLager.setEnabled(false);
        jButtonHoger.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonHoger = new javax.swing.JButton();
        jLabelOutput = new javax.swing.JLabel();
        jButtonCorrect = new javax.swing.JButton();
        jButtonLager = new javax.swing.JButton();
        jButtonAfsluiten = new javax.swing.JButton();
        jButtonNieuw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonHoger.setText("Hoger!");
        jButtonHoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHogerActionPerformed(evt);
            }
        });

        jLabelOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOutput.setText("Kies, mentaal, een getal tussen 0 en 500 en klik op Nieuw.");

        jButtonCorrect.setText("Correct!");
        jButtonCorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorrectActionPerformed(evt);
            }
        });

        jButtonLager.setText("Lager!");
        jButtonLager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLager, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHoger, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHoger)
                    .addComponent(jButtonCorrect)
                    .addComponent(jButtonLager))
                .addGap(34, 34, 34)
                .addComponent(jLabelOutput)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButtonAfsluiten.setText("Afsluiten");
        jButtonAfsluiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfsluitenActionPerformed(evt);
            }
        });

        jButtonNieuw.setText("Nieuw");
        jButtonNieuw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNieuwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNieuw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAfsluiten)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNieuw)
                    .addComponent(jButtonAfsluiten))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHogerActionPerformed
        spel.getPlayerResult(1);
        doeBeurt();
    }//GEN-LAST:event_jButtonHogerActionPerformed

    private void jButtonNieuwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNieuwActionPerformed
        spel.resetSpel();
        jLabelOutput.setText("");
        jButtonHoger.setEnabled(true);
        jButtonCorrect.setEnabled(true);
        jButtonLager.setEnabled(true);        
        
        int gok = spel.doeGok();            
        jLabelOutput.setText("De computer gokt: " + gok + ". Wat is uw antwoord?");
    }//GEN-LAST:event_jButtonNieuwActionPerformed

    private void jButtonAfsluitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfsluitenActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonAfsluitenActionPerformed

    private void jButtonLagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLagerActionPerformed
        spel.getPlayerResult(-1);
        doeBeurt();
    }//GEN-LAST:event_jButtonLagerActionPerformed

    private void jButtonCorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorrectActionPerformed
            jLabelOutput.setText("Jammer. U verloor...");
            jButtonCorrect.setEnabled(false);
            jButtonLager.setEnabled(false);
            jButtonHoger.setEnabled(false);
    }//GEN-LAST:event_jButtonCorrectActionPerformed

    private void doeBeurt(){
        if( spel.geefResterendeBeurten() == 0){
            jLabelOutput.setText("Gefeliciteerd. U won!");
            jButtonCorrect.setEnabled(false);
            jButtonLager.setEnabled(false);
            jButtonHoger.setEnabled(false);
        } else{
            int gok = spel.doeGok();            
            jLabelOutput.setText("De computer gokt: " + gok + ". Wat is uw antwoord?");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HogerLager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HogerLager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HogerLager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HogerLager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HogerLager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfsluiten;
    private javax.swing.JButton jButtonCorrect;
    private javax.swing.JButton jButtonHoger;
    private javax.swing.JButton jButtonLager;
    private javax.swing.JButton jButtonNieuw;
    private javax.swing.JLabel jLabelOutput;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
